//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D12.ChatGPT.WebAdmin.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D12.ChatGPT.WebAdmin.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        internal static string BackToLogin
        {
            get
            {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        internal static string ConfirmAccountSubject
        {
            get
            {
                return ResourceManager.GetString("ConfirmAccountSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with *PROVIDER*. Please enter a user name for this site below and click the Register button to finish logging in..
        /// </summary>
        internal static string ExternalLoginConfirmDesc
        {
            get
            {
                return ResourceManager.GetString("ExternalLoginConfirmDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Associate your *PROVIDER* account..
        /// </summary>
        internal static string ExternalLoginConfirmTitle
        {
            get
            {
                return ResourceManager.GetString("ExternalLoginConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPass
        {
            get
            {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassLink
        {
            get
            {
                return ResourceManager.GetString("ForgotPassLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I Accept.
        /// </summary>
        internal static string IAccept
        {
            get
            {
                return ResourceManager.GetString("IAccept", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your email to receive instructions.
        /// </summary>
        internal static string LblForgotPass
        {
            get
            {
                return ResourceManager.GetString("LblForgotPass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginBtn
        {
            get
            {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please, verify email and password, and try again..
        /// </summary>
        internal static string LoginFailureMsg
        {
            get
            {
                return ResourceManager.GetString("LoginFailureMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string LoginFailureTitle
        {
            get
            {
                return ResourceManager.GetString("LoginFailureTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please call to support.
        /// </summary>
        internal static string LoginLockedOutMsg
        {
            get
            {
                return ResourceManager.GetString("LoginLockedOutMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        internal static string LoginLockedOutTitle
        {
            get
            {
                return ResourceManager.GetString("LoginLockedOutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logged Successfully.
        /// </summary>
        internal static string LoginSuccessMsg
        {
            get
            {
                return ResourceManager.GetString("LoginSuccessMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        internal static string LoginSuccessTitle
        {
            get
            {
                return ResourceManager.GetString("LoginSuccessTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your login information.
        /// </summary>
        internal static string LoginTitle
        {
            get
            {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login with .
        /// </summary>
        internal static string LoginWithExternal
        {
            get
            {
                return ResourceManager.GetString("LoginWithExternal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string PasswordConfirm
        {
            get
            {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterBtn
        {
            get
            {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We send a confirmation mail to your email address. Please check your email, don&apos;t forget to check in spam folder, and confirm your email address..
        /// </summary>
        internal static string RegisterFailMsg
        {
            get
            {
                return ResourceManager.GetString("RegisterFailMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The email address already exists, please check and try again. If you forgot the password, try password recovering..
        /// </summary>
        internal static string RegisterFailMsgEmailExist
        {
            get
            {
                return ResourceManager.GetString("RegisterFailMsgEmailExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email already taken.
        /// </summary>
        internal static string RegisterFailTitleEmailExist
        {
            get
            {
                return ResourceManager.GetString("RegisterFailTitleEmailExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I want to register.
        /// </summary>
        internal static string RegisterLinkText
        {
            get
            {
                return ResourceManager.GetString("RegisterLinkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We send a confirmation mail to your email address. Please check your email, don&apos;t forget to check in spam folder, and confirm your email address..
        /// </summary>
        internal static string RegisterSuccessMsg
        {
            get
            {
                return ResourceManager.GetString("RegisterSuccessMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully Registered.
        /// </summary>
        internal static string RegisterSuccessTitle
        {
            get
            {
                return ResourceManager.GetString("RegisterSuccessTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string RegisterTitle
        {
            get
            {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string Remember
        {
            get
            {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We have sent an email with a confirmation link to your email address. Please allow 5-10 minutes for this message to arrive. Don&apos;t forget to check spam folder..
        /// </summary>
        internal static string RequiresVerificationMsg
        {
            get
            {
                return ResourceManager.GetString("RequiresVerificationMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pending Verification.
        /// </summary>
        internal static string RequiresVerificationTitle
        {
            get
            {
                return ResourceManager.GetString("RequiresVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send again the email with the link verification.
        /// </summary>
        internal static string ResendVerificationEmailLink
        {
            get
            {
                return ResourceManager.GetString("ResendVerificationEmailLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        internal static string SendPassBtn
        {
            get
            {
                return ResourceManager.GetString("SendPassBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Or Login Using.
        /// </summary>
        internal static string TitleExternalLogin
        {
            get
            {
                return ResourceManager.GetString("TitleExternalLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve Password.
        /// </summary>
        internal static string TitleForgotPass
        {
            get
            {
                return ResourceManager.GetString("TitleForgotPass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the terms of use.
        /// </summary>
        internal static string UserAgreement
        {
            get
            {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
    }
}
